name: plolitik

networks:
  traefik:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plolitik.rule=Host(`eu.oskar.global`)"
      - "traefik.http.routers.plolitik.entrypoints=websecure"
      - "traefik.http.routers.plolitik.tls.certresolver=cloudflare"
      - "traefik.http.routers.plolitik.service=plolitik"
      - "traefik.http.services.plolitik.loadbalancer.server.port=3000"
